name: Docker CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub (optional)
      if: false
      run: echo "Login if needed"

    - name: Build Docker Image
      run: docker build -t flask-docker-ci .

    - name: Run Tests with Pytest inside Docker
      run: |
        docker run --rm flask-docker-ci pytest
